[package]
name = "match3"
version = "0.1.0"
authors = ["Philip Trauner <philip.trauner@aol.com>"]

[[bin]]
name = "match3"

[dependencies]
piston = "0.31.1"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"
rand="0.3.12"
lazy_static = "0.1.*"